"""Gradio web UI for The Unofficial Guide (Milestone 5).

Run from the repo root (after building the index with `python run_index.py`):

    python app.py

Opens a local web page where you can ask a question about UCSC dining. The
answer is generated by Groq, grounded only on the retrieved chunks, and the
source passages (with cosine distances) are shown below so you can verify
the answer against its evidence.
"""

from __future__ import annotations

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

import gradio as gr  # noqa: E402

from generate import answer  # noqa: E402

EXAMPLE_QUESTIONS = [
    "What are the operating hours of the College Nine / John R. Lewis dining hall?",
    "Can I use Banana Bucks at any dining hall, and do they roll over between quarters?",
    "Which dining hall do UCSC students consider the best, and why?",
    "What off-campus restaurants near UCSC do students recommend?",
    "How much have dining hall prices risen recently?",
]


def respond(question: str):
    if not question or not question.strip():
        return "Please enter a question.", ""
    try:
        text, results = answer(question)
    except Exception as exc:  # noqa: BLE001 - surface setup errors in the UI
        return f"Error: {exc}", ""

    sources_md = "\n".join(
        f"**[{i}]** {r.source} — distance {r.distance:.2f}  \n{r.url}"
        for i, r in enumerate(results, 1)
    )
    return text, sources_md


with gr.Blocks(title="The Unofficial Guide — UCSC Dining") as demo:
    gr.Markdown(
        "# 🍴 The Unofficial Guide — UCSC Dining\n"
        "Ask about dining halls, meal plans (Slug Points / Banana Bucks / Flexi "
        "Dollars), or off-campus restaurants. Answers are grounded only on "
        "student reviews and official info, with sources shown below."
    )
    question = gr.Textbox(
        label="Your question",
        placeholder="e.g. Which dining hall has the best food?",
        lines=2,
    )
    ask = gr.Button("Ask", variant="primary")
    answer_box = gr.Markdown(label="Answer")
    with gr.Accordion("Sources (retrieved passages)", open=True):
        sources_box = gr.Markdown()

    ask.click(respond, inputs=question, outputs=[answer_box, sources_box])
    question.submit(respond, inputs=question, outputs=[answer_box, sources_box])
    gr.Examples(EXAMPLE_QUESTIONS, inputs=question)


if __name__ == "__main__":
    demo.launch()
